# Generated by Django 5.2.9 on 2026-01-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('permission_code', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
