# Generated by Django 5.2.9 on 2026-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0002_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
