# Generated by Django 5.2.9 on 2026-02-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0004_logaktivitas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAktivitas',
        ),
    ]
