# Generated by Django 5.2.9 on 2026-01-06 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSimpanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(choices=[('POKOK', 'Simpanan Pokok'), ('WAJIB', 'Simpanan Wajib'), ('SUKARELA', 'Simpanan Sukarela')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'jenis_simpanan',
            },
        ),
        migrations.CreateModel(
            name='HistoryTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis_transaksi', models.CharField(choices=[('SETOR', 'Setor'), ('TARIK', 'Tarik')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'history_transaksi',
            },
        ),
        migrations.CreateModel(
            name='Penarikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penarikan', to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
                ('petugas', models.ForeignKey(limit_choices_to={'role': 'bendahara'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'penarikan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Simpanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dana_sosial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simpanan', to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
                ('petugas', models.ForeignKey(limit_choices_to={'role': 'bendahara'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simpanan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
