# Generated by Django 5.2.9 on 2026-01-07 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_alter_anggota_no_telp'),
        ('simpanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penarikan',
            name='petugas',
        ),
        migrations.RemoveField(
            model_name='simpanan',
            name='petugas',
        ),
        migrations.AddField(
            model_name='penarikan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simpanan',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penarikan',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='simpanan',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='HistoryTabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('jenis_transaksi', models.CharField(choices=[('SETOR', 'Setor'), ('TARIK', 'Tarik'), ('KOREKSI', 'Koreksi')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=18)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jenis_simpanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpanan.jenissimpanan')),
            ],
            options={
                'db_table': 'history_tabungan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.DeleteModel(
            name='HistoryTransaksi',
        ),
    ]
