# Generated by Django 5.2.9 on 2026-01-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_alter_pinjaman_id_admin_and_more'),
        ('simpanan', '0002_remove_penarikan_petugas_remove_simpanan_petugas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpanan',
            name='sumber_pinjaman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinjaman.pinjaman'),
        ),
    ]
