# Generated by Django 5.2.9 on 2026-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0002_remove_penarikan_petugas_remove_simpanan_petugas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenissimpanan',
            name='nama_jenis',
            field=models.CharField(choices=[('Pokok', 'Simpanan Pokok'), ('Wajib', 'Simpanan Wajib'), ('Sukarela', 'Simpanan Sukarela')], max_length=20, unique=True),
        ),
    ]
