# Generated by Django 5.2.9 on 2026-03-08 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_alter_pinjaman_id_admin_and_more'),
        ('simpanan', '0003_simpanan_sumber_pinjaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytabungan',
            name='sumber_pinjaman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinjaman.pinjaman'),
        ),
    ]
