# Generated by Django 5.2.9 on 2026-04-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0003_alter_jenissimpanan_nama_jenis'),
        ('simpanan', '0004_historytabungan_sumber_pinjaman'),
    ]

    operations = [
    ]
