# Generated by Django 5.2.9 on 2026-04-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0005_merge_20260403_1023'),
        ('simpanan', '0005_merge_20260403_1037'),
    ]

    operations = [
    ]
