# Generated by Django 5.2.9 on 2026-04-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0006_merge_20260412_2324'),
        ('simpanan', '0006_merge_20260414_1035'),
    ]

    operations = [
    ]
