# Generated by Django 5.2.9 on 2026-04-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0007_merge_20260419_1848'),
        ('simpanan', '0007_merge_20260419_2026'),
    ]

    operations = [
    ]
