# Generated by Django 5.2.9 on 2026-01-05 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('nomor_anggota', models.CharField(default='0', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField(blank=True, null=True)),
                ('nip', models.CharField(blank=True, max_length=30, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_daftar', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=15)),
                ('alasan_nonaktif', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_nonaktif', models.DateField(blank=True, null=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Anggota',
            },
        ),
    ]
