# Generated by Django 5.2.9 on 2026-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
