# Generated by Django 5.2.9 on 2026-01-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_alter_anggota_email_alter_anggota_pekerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='no_telp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
