# Generated by Django 5.2.9 on 2026-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_alter_anggota_no_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nomor_anggota',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
