# Generated by Django 5.2.9 on 2026-02-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0004_alter_anggota_nomor_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='alamat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='no_telp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='pekerjaan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='umur',
            field=models.IntegerField(null=True),
        ),
    ]
