# Generated by Django 5.2.9 on 2026-03-01 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0005_alter_anggota_alamat_alter_anggota_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='tanggal_daftar',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
