# Generated by Django 5.2.9 on 2026-01-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0004_alter_anggota_nomor_anggota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPinjaman',
            fields=[
                ('id_jenis_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(choices=[('Reguler', 'Reguler'), ('Khusus', 'Khusus'), ('Barang', 'Barang')], max_length=50)),
            ],
            options={
                'db_table': 'Jenis_Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='KategoriJasa',
            fields=[
                ('id_kategori_jasa', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategori_jasa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Kategori_Jasa',
            },
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id_pinjaman', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('angsuran_per_bulan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('jasa_persen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jasa_rupiah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tanggal_meminjam', models.DateField()),
                ('jatuh_tempo', models.PositiveIntegerField(help_text='Lama pinjaman dalam bulan')),
                ('sisa_pinjaman', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(max_length=20)),
                ('id_admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_jenis_pinjaman', models.ForeignKey(db_column='jenis_pinjaman_id', on_delete=django.db.models.deletion.CASCADE, to='pinjaman.jenispinjaman')),
                ('id_kategori_jasa', models.ForeignKey(db_column='kategori_jasa_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa')),
                ('nomor_anggota', models.ForeignKey(db_column='anggota_id', on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
            options={
                'db_table': 'Pinjaman',
            },
        ),
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id_pembayaran', models.BigAutoField(primary_key=True, serialize=False)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tanggal_bayar', models.DateField()),
                ('tipe_bayar', models.CharField(choices=[('cicilan', 'Cicilan + Jasa'), ('jasa', 'Jasa Saja')], default='cicilan', max_length=10)),
                ('id_admin', models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angsuran_admin', to=settings.AUTH_USER_MODEL)),
                ('id_pinjaman', models.ForeignKey(db_column='id_pinjaman', on_delete=django.db.models.deletion.CASCADE, to='pinjaman.pinjaman')),
            ],
            options={
                'db_table': 'Angsuran',
            },
        ),
    ]
