# Generated by Django 5.2.9 on 2026-01-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0004_alter_anggota_nomor_anggota'),
        ('pinjaman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjaman',
            name='id_admin',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='id_jenis_pinjaman',
            field=models.ForeignKey(db_column='jenis_pinjaman_id', on_delete=django.db.models.deletion.CASCADE, to='pinjaman.jenispinjaman'),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='id_kategori_jasa',
            field=models.ForeignKey(db_column='kategori_jasa_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjaman.kategorijasa'),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='nomor_anggota',
            field=models.ForeignKey(db_column='anggota_id', on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota'),
        ),
    ]
