# Generated by Django 5.2.9 on 2026-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_alter_pinjaman_id_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angsuran',
            name='jumlah_pokok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
