# Generated by Django 5.2.9 on 2026-05-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0003_angsuran_jumlah_pokok'),
    ]

    operations = [
        migrations.AddField(
            model_name='angsuran',
            name='bulan_kewajiban',
            field=models.DateField(blank=True, help_text='Tanggal pertama bulan kewajiban cicilan ini (YYYY-MM-01)', null=True),
        ),
    ]
