# Generated by Django 5.2.9 on 2026-09-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0004_angsuran_bulan_kewajiban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angsuran',
            name='tipe_bayar',
            field=models.CharField(choices=[('cicilan', 'Cicilan + Jasa'), ('pokok', 'Pokok Saja'), ('jasa', 'Jasa Saja')], default='cicilan', max_length=10),
        ),
    ]
